[Ilwis]
Description=calculate sun and msg satellite azimuth angles          
Time=1269967898
Version=3.1
Class=Script
Type=Script
[Script]
ScriptFile=create_azimuth_angle_maps.isf
NrParams=0
[Params]
Param0=year
Type0=value
Ext0=Yes
Param1=month
Type1=value
Ext1=No
DefaultValue0=2008
DefaultValue1=6
Param2=day     
Type2=value
Ext2=No
Param3=time of day (UTC)
Type3=value
Ext3=No
Param4=time
Type4=value
Ext4=No
DefaultValue2=21
DefaultValue3=20
